<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Strict//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php echo $this->headTitle(); ?>
<script type="text/javascript" src="/framework/externals/dojo/dojo/dojo.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(), '/public/js/index.js'; ?>"></script>
</head>
<body>
<h1>Outro Layout</h1>
<br>
<?php echo $this->layout()->content; ?>
</body>
</html>